name: Deploy Bicep Template at Tenant Scope

on:
  workflow_dispatch: # manual trigger, can also add push or schedule
  push:
    branches:
      - main

env:
  TEMPLATE_FILE: ./XXXXX

jobs:
  Build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      #Checkout your repo
      - name: Checkout
        uses: actions/checkout@v4

      # Azure Login with Service Principal
      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.username }} \
            --password ${{ secrets.password }} \
            --tenant ${{ secrets.tenant }}
          az account set --subscription ${{ secrets.subscription_id }}
          
      - name: Build Bicep template
        id: build_bicep
        run: |
          mkdir -p build
          OUTPUT_FILE="build/template.json"
          az bicep build --file "${{ env.TEMPLATE_FILE }}" --outdir build
          echo "filepath=$OUTPUT_FILE" >> $GITHUB_OUTPUT
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-output
          path: build/template.json


  deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure Login with Service Principal
      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.username }} \
            --password ${{ secrets.password }} \
            --tenant ${{ secrets.tenant }}
          az account set --subscription ${{ secrets.subscription_id }}
      #Deploy Bicep at tenant scope
      - name: Deploy Bicep
        run: |
          az deployment sub create \
            --name DEPLOYMENT_BICEP \
            --location eastus2 \
            --template-file ./XXXXXXX \
            --parameters subscriptionId=${{ secrets.subscription_id }} \
            --only-show-errors --output table
      - name: Azure Logout
        run: az logout
